"""Plan and simulate an expert path for original Piper gripper -> pipette handoff.

The first task is:
1. Open the left/original Piper gripper.
2. Move to a pipette-aligned pregrasp without colliding with the rack.
3. Move into grasp range, close the gripper.
4. Lift the pipette away from the rack.
5. Move the pipette toward the midpoint between the two arms, facing the
   Piper+Aero palm.

The exported trajectory is generated by MuJoCo dynamics playback: the arm and
gripper are controlled through position actuators, while the pipette remains a
freejoint object moved only by contact and friction.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import sys

import imageio.v2 as imageio
import numpy as np
from scipy.spatial.transform import Rotation, Slerp


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from aero_tasks.motion_planning import (  # noqa: E402
    CollisionPolicy,
    JointGroup,
    PlanningModel,
    RRTConnectConfig,
    RRTConnectPlanner,
    normalize,
    solve_body_pose_ik,
)
from aero_tasks.payload_collision import (  # noqa: E402
    CarriedPayloadState,
    check_carried_payload_path,
    measure_carried_payload_state,
)
from aero_tasks.task_sampling import (  # noqa: E402
    apply_episode_spec_to_model,
    apply_episode_spec_to_qpos,
    load_episode_spec,
)

try:
    import mujoco
except ImportError as exc:  # pragma: no cover
    raise SystemExit(f"Missing dependency: {exc}") from exc


DEFAULT_MODEL = PROJECT_ROOT / "models/piper_aero_hand/scenes/Piper_dual_pipette_rack_table.xml"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "outputs/piper_gripper_pipette_handoff"

LEFT_ARM_JOINTS = tuple(f"piper_original/joint{i}" for i in range(1, 7))
LEFT_GRIPPER_JOINTS = ("piper_original/joint7", "piper_original/joint8")
LEFT_HOME = np.array([0.0, 1.57, -1.3485, 0.0, 0.0, 0.0], dtype=np.float64)
PIPETTE_GRASP_SITE_OFFSET_M = 0.12
LIFT_CLEARANCE_M = 0.03
PIPETTE_HOOK_REFERENCE_LOCAL = np.array(
    [-0.02251656, -0.00070474, 0.17342691],
    dtype=np.float64,
)
HANDOFF_TARGET_SITE = "piper_aerohand/aero_index_proximal_site"
HANDOFF_TARGET_BODY = "piper_aerohand/right_index_proximal_link"
HANDOFF_TARGET_AXIS_LOCAL = np.array([0.0, 0.0, 1.0], dtype=np.float64)
HANDOFF_TARGET_SURFACE_OFFSET_M = 0.008
HANDOFF_TARGET_VERTICAL_OFFSET_M = 0.015
HANDOFF_STANDOFF_M = 0.05
HANDOFF_SETTLE_COMMANDS = 5
RELEASE_COMMANDS = 18
PIPER_RETREAT_M = 0.08
HANDOFF_LOCAL_Y_WORLD_Z_TOLERANCE = 0.03
MAX_HANDOFF_ROLL_DEG = 45.0
PALM_CLOSE_MIN_STEPS = 160
PALM_CLOSE_MAX_STEPS = 1400
PALM_CLOSE_LIMIT_MARGIN_RAD = 0.01
PALM_CLOSE_LIMIT_TOLERANCE_RAD = 0.025
PALM_CLOSE_STOP_SPEED_RAD_S = 0.02
HANDOFF_TOP_TOLERANCE_M = 0.004
HANDOFF_CONTACT_TOP_TOLERANCE_M = 0.006
HANDOFF_AXIS_TOLERANCE_M = 0.005
HANDOFF_HOOK_TARGET_TOLERANCE_M = 0.012
HANDOFF_CORRECTION_ATTEMPTS = 3
HANDOFF_CORRECTION_GAIN = 0.6
PALM_GRASP_FINGERS = ("index", "middle", "ring", "pinky")
PALM_TIP_GEOMS = {
    "index": "if_tip",
    "middle": "mf_tip",
    "ring": "rf_tip",
    "pinky": "pf_tip",
}
PALM_GRASP_KP = 2.00
PALM_GRASP_KD = 0.04
PALM_GRASP_MAX_TORQUE = 1.50


def set_joint(planner: PlanningModel, qpos: np.ndarray, joint_name: str, value: float) -> None:
    jid = planner.joint_id(joint_name)
    qpos[int(planner.model.jnt_qposadr[jid])] = float(value)


def set_left_gripper(planner: PlanningModel, qpos: np.ndarray, opening: float) -> None:
    opening = float(np.clip(opening, 0.0, 0.035))
    set_joint(planner, qpos, LEFT_GRIPPER_JOINTS[0], opening)
    set_joint(planner, qpos, LEFT_GRIPPER_JOINTS[1], -opening)


def actuator_index(model, name: str) -> int | None:
    aid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, name)
    return None if aid < 0 else int(aid)


def set_ctrl_for_q(planner: PlanningModel, ctrl: np.ndarray, group: JointGroup, q: np.ndarray) -> None:
    for joint_name, value in zip(group.names, q, strict=True):
        aid = actuator_index(planner.model, joint_name)
        if aid is not None:
            ctrl[aid] = float(value)


def interpolate_path(path: np.ndarray, max_step: float = 0.035) -> np.ndarray:
    dense: list[np.ndarray] = []
    for start, end in zip(path[:-1], path[1:], strict=False):
        if not dense:
            dense.append(start.copy())
        distance = float(np.linalg.norm(end - start))
        steps = max(2, int(np.ceil(distance / max(max_step, 1e-6))) + 1)
        for alpha in np.linspace(0.0, 1.0, steps)[1:]:
            dense.append((1.0 - alpha) * start + alpha * end)
    if not dense:
        dense.append(path[0].copy())
    return np.asarray(dense, dtype=np.float64)


def make_qpos_from_arm(planner: PlanningModel, group: JointGroup, template: np.ndarray, q: np.ndarray) -> np.ndarray:
    qpos = template.copy()
    planner.set_joint_group(qpos, group, q)
    return qpos


def is_valid_q(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    q: np.ndarray,
    policy: CollisionPolicy,
) -> bool:
    qpos = make_qpos_from_arm(planner, group, template, q)
    planner.forward(qpos)
    return not any(policy.is_forbidden(*pair) for pair in planner.contact_pairs())


def make_rrt(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    policy: CollisionPolicy,
    *,
    seed: int,
) -> RRTConnectPlanner:
    def state_valid(q: np.ndarray) -> bool:
        return is_valid_q(planner, group, template, q, policy)

    return RRTConnectPlanner(
        group.lower,
        group.upper,
        state_valid,
        config=RRTConnectConfig(
            step_size=0.11,
            edge_resolution=0.025,
            max_iterations=7000,
            timeout_s=10.0,
            shortcut_attempts=160,
            seed=seed,
        ),
    )


def gripper_center_offset_local(planner: PlanningModel, qpos: np.ndarray) -> np.ndarray:
    planner.forward(qpos)
    link6_id = planner.body_id("piper_original/link6")
    link7_id = planner.body_id("piper_original/link7")
    link8_id = planner.body_id("piper_original/link8")
    link6_pos = planner.data.xpos[link6_id].copy()
    link6_R = planner.data.xmat[link6_id].reshape(3, 3).copy()
    center = 0.5 * (planner.data.xpos[link7_id] + planner.data.xpos[link8_id])
    return link6_R.T @ (center - link6_pos)


def target_link6_pose(tcp_pos: np.ndarray, tcp_R: np.ndarray, tcp_offset_local: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    return tcp_pos - tcp_R @ tcp_offset_local, tcp_R


def level_side_grasp_frames(pipette_axis: np.ndarray, reference_R: np.ndarray) -> list[np.ndarray]:
    """Return equivalent side-grasp frames with local Y parallel to the ground."""

    world_z = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    frames: list[np.ndarray] = []
    for x_sign in (1.0, -1.0):
        x_axis = x_sign * normalize(pipette_axis)
        y_axis = np.cross(x_axis, world_z)
        if float(np.linalg.norm(y_axis)) < 1e-8:
            y_axis = reference_R[:, 1] - world_z * float(np.dot(reference_R[:, 1], world_z))
        y_axis = normalize(y_axis)
        for y_sign in (1.0, -1.0):
            candidate_y = y_sign * y_axis
            z_axis = normalize(np.cross(x_axis, candidate_y))
            frames.append(np.stack([x_axis, candidate_y, z_axis], axis=1))
    return sorted(
        frames,
        key=lambda frame: float(Rotation.from_matrix(frame @ reference_R.T).magnitude()),
    )


def level_gripper_y_path(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    path: np.ndarray,
    collision_policy: CollisionPolicy,
    *,
    max_step: float = 0.02,
) -> np.ndarray:
    """Use wrist roll to keep link6 local Y horizontal along a joint path."""

    dense_path = interpolate_path(np.asarray(path, dtype=np.float64), max_step=max_step)
    link6_id = planner.body_id("piper_original/link6")
    leveled: list[np.ndarray] = []
    previous_roll = float(dense_path[0, -1])

    for q in dense_path:
        candidate = q.copy()
        candidate[-1] = 0.0
        qpos = make_qpos_from_arm(planner, group, template, candidate)
        planner.forward(qpos)
        zero_roll_R = planner.data.xmat[link6_id].reshape(3, 3)

        # For R(q6) = R(0) RotZ(q6), solve world_z dot local_Y(q6) = 0.
        base_roll = float(np.arctan2(zero_roll_R[2, 1], zero_roll_R[2, 0]))
        roll_candidates = [
            base_roll + k * np.pi
            for k in range(-3, 4)
            if group.lower[-1] <= base_roll + k * np.pi <= group.upper[-1]
        ]
        if not roll_candidates:
            raise RuntimeError("No joint6 value can keep the gripper local Y axis horizontal")
        candidate[-1] = min(roll_candidates, key=lambda value: abs(value - previous_roll))
        previous_roll = float(candidate[-1])

        qpos = make_qpos_from_arm(planner, group, template, candidate)
        planner.forward(qpos)
        if any(collision_policy.is_forbidden(*pair) for pair in planner.contact_pairs()):
            raise RuntimeError("Level-wrist path introduced a forbidden collision")
        leveled.append(candidate)

    return np.asarray(leveled, dtype=np.float64)


def build_candidate_frames(target_R: np.ndarray, roll_axis: np.ndarray) -> list[np.ndarray]:
    _ = roll_axis
    return [target_R]


def find_stage_ik(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    link6_body: str,
    tcp_pos: np.ndarray,
    target_R: np.ndarray,
    roll_axis: np.ndarray,
    tcp_offset_local: np.ndarray,
    seed_q: np.ndarray,
    collision_policy: CollisionPolicy | None,
    rng: np.random.Generator,
    max_tcp_error: float = 0.075,
    ik_regularization: float = 0.03,
) -> tuple[np.ndarray, np.ndarray, float]:
    random_seeds = [
        rng.uniform(group.lower, group.upper),
        np.clip(seed_q + rng.normal(0.0, 0.35, size=seed_q.shape), group.lower, group.upper),
        LEFT_HOME,
    ]
    best: tuple[np.ndarray, np.ndarray, float, float] | None = None
    for candidate_R in build_candidate_frames(target_R, roll_axis):
        target_pos, target_link6_R = target_link6_pose(tcp_pos, candidate_R, tcp_offset_local)
        try:
            q, cost = solve_body_pose_ik(
                planner,
                group,
                link6_body,
                target_pos,
                target_link6_R,
                seed=seed_q,
                extra_seeds=random_seeds,
                collision_policy=collision_policy,
                fixed_qpos=template,
                regularization_weight=ik_regularization,
            )
        except RuntimeError:
            continue
        qpos = make_qpos_from_arm(planner, group, template, q)
        planner.forward(qpos)
        link6_pos = planner.data.xpos[planner.body_id(link6_body)].copy()
        link6_R = planner.data.xmat[planner.body_id(link6_body)].reshape(3, 3).copy()
        tcp_actual = link6_pos + link6_R @ tcp_offset_local
        tcp_error = float(np.linalg.norm(tcp_actual - tcp_pos))
        continuity_error = float(np.linalg.norm(q - seed_q))
        wrist_roll_error = abs(float(q[-1] - seed_q[-1]))
        score = tcp_error + 0.01 * cost + 0.02 * continuity_error + 0.08 * wrist_roll_error
        if best is None or score < best[3]:
            best = (q, candidate_R, tcp_error, score)
    if best is None:
        raise RuntimeError("No IK candidate solved")
    if best[2] > max_tcp_error:
        raise RuntimeError(f"No IK candidate reached the TCP target closely enough: error={best[2]:.4f}m")
    return best[0], best[1], best[2]


def plan_cartesian_tcp_path(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    link6_body: str,
    start_tcp_pos: np.ndarray,
    end_tcp_pos: np.ndarray,
    target_R: np.ndarray,
    tcp_offset_local: np.ndarray,
    start_q: np.ndarray,
    collision_policy: CollisionPolicy | None,
    *,
    max_tcp_step: float = 0.015,
    max_tcp_error: float = 0.035,
    regularization_weight: float = 0.35,
) -> tuple[np.ndarray, float]:
    """Build a continuous Cartesian TCP path with fixed gripper orientation."""

    start_tcp_pos = np.asarray(start_tcp_pos, dtype=np.float64).reshape(3)
    end_tcp_pos = np.asarray(end_tcp_pos, dtype=np.float64).reshape(3)
    distance = float(np.linalg.norm(end_tcp_pos - start_tcp_pos))
    steps = max(2, int(np.ceil(distance / max(max_tcp_step, 1e-6))) + 1)
    path = [np.asarray(start_q, dtype=np.float64).copy()]
    worst_error = 0.0
    seed_q = path[-1]
    target_link6_R = np.asarray(target_R, dtype=np.float64).reshape(3, 3)

    for alpha in np.linspace(0.0, 1.0, steps)[1:]:
        tcp_pos = (1.0 - alpha) * start_tcp_pos + alpha * end_tcp_pos
        target_pos, target_body_R = target_link6_pose(tcp_pos, target_link6_R, tcp_offset_local)
        try:
            q, _ = solve_body_pose_ik(
                planner,
                group,
                link6_body,
                target_pos,
                target_body_R,
                seed=seed_q,
                collision_policy=collision_policy,
                fixed_qpos=template,
                regularization_weight=regularization_weight,
                max_nfev=350,
            )
        except RuntimeError as exc:
            raise RuntimeError(
                "Cartesian IK failed "
                f"at alpha={alpha:.3f}, tcp_pos={tcp_pos.tolist()}"
            ) from exc
        qpos = make_qpos_from_arm(planner, group, template, q)
        planner.forward(qpos)
        link6_pos = planner.data.xpos[planner.body_id(link6_body)].copy()
        link6_R = planner.data.xmat[planner.body_id(link6_body)].reshape(3, 3).copy()
        tcp_actual = link6_pos + link6_R @ tcp_offset_local
        tcp_error = float(np.linalg.norm(tcp_actual - tcp_pos))
        if tcp_error > max_tcp_error:
            raise RuntimeError(f"Cartesian IK waypoint missed TCP target: error={tcp_error:.4f}m")
        worst_error = max(worst_error, tcp_error)
        path.append(q.copy())
        seed_q = q

    return np.asarray(path, dtype=np.float64), worst_error


def plan_cartesian_tcp_pose_path(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    link6_body: str,
    start_tcp_pos: np.ndarray,
    end_tcp_pos: np.ndarray,
    start_R: np.ndarray,
    end_R: np.ndarray,
    tcp_offset_local: np.ndarray,
    start_q: np.ndarray,
    collision_policy: CollisionPolicy | None,
    *,
    max_tcp_step: float = 0.015,
    max_rotation_step_rad: float = np.deg2rad(5.0),
    max_tcp_error: float = 0.05,
    regularization_weight: float = 0.35,
) -> tuple[np.ndarray, float]:
    """Build a continuous Cartesian path with shortest-arc orientation interpolation."""

    start_tcp_pos = np.asarray(start_tcp_pos, dtype=np.float64).reshape(3)
    end_tcp_pos = np.asarray(end_tcp_pos, dtype=np.float64).reshape(3)
    start_R = np.asarray(start_R, dtype=np.float64).reshape(3, 3)
    end_R = np.asarray(end_R, dtype=np.float64).reshape(3, 3)
    translation_distance = float(np.linalg.norm(end_tcp_pos - start_tcp_pos))
    rotation_distance = float(Rotation.from_matrix(end_R @ start_R.T).magnitude())
    steps = max(
        2,
        int(np.ceil(translation_distance / max(max_tcp_step, 1e-6))) + 1,
        int(np.ceil(rotation_distance / max(max_rotation_step_rad, 1e-6))) + 1,
    )
    alphas = np.linspace(0.0, 1.0, steps)
    orientation_path = Slerp(
        [0.0, 1.0],
        Rotation.from_matrix(np.stack([start_R, end_R])),
    )(alphas).as_matrix()

    path = [np.asarray(start_q, dtype=np.float64).copy()]
    seed_q = path[-1]
    worst_error = 0.0
    for index, alpha in enumerate(alphas[1:], start=1):
        tcp_pos = (1.0 - alpha) * start_tcp_pos + alpha * end_tcp_pos
        target_R = orientation_path[index]
        target_pos, target_body_R = target_link6_pose(tcp_pos, target_R, tcp_offset_local)
        try:
            q, _ = solve_body_pose_ik(
                planner,
                group,
                link6_body,
                target_pos,
                target_body_R,
                seed=seed_q,
                collision_policy=collision_policy,
                fixed_qpos=template,
                regularization_weight=regularization_weight,
                max_nfev=400,
            )
        except RuntimeError as exc:
            raise RuntimeError(
                "Cartesian pose IK failed "
                f"at alpha={alpha:.3f}, tcp_pos={tcp_pos.tolist()}"
            ) from exc
        qpos = make_qpos_from_arm(planner, group, template, q)
        planner.forward(qpos)
        link6_pos = planner.data.xpos[planner.body_id(link6_body)].copy()
        link6_R = planner.data.xmat[planner.body_id(link6_body)].reshape(3, 3).copy()
        tcp_actual = link6_pos + link6_R @ tcp_offset_local
        tcp_error = float(np.linalg.norm(tcp_actual - tcp_pos))
        if tcp_error > max_tcp_error:
            raise RuntimeError(f"Cartesian pose IK waypoint missed TCP target: error={tcp_error:.4f}m")
        worst_error = max(worst_error, tcp_error)
        path.append(q.copy())
        seed_q = q

    return np.asarray(path, dtype=np.float64), worst_error


def site_world_position(planner: PlanningModel, site_name: str) -> np.ndarray:
    site_id = mujoco.mj_name2id(planner.model, mujoco.mjtObj.mjOBJ_SITE, site_name)
    if site_id < 0:
        raise ValueError(f"Missing site {site_name!r}")
    return planner.data.site_xpos[site_id].copy()


def target_handoff_frame(
    target_axis: np.ndarray,
    target_center: np.ndarray,
    current_hook_position: np.ndarray,
    reference_R: np.ndarray,
) -> np.ndarray:
    """Construct a mostly horizontal handoff frame whose +Z is perpendicular to target_axis."""

    target_axis = normalize(target_axis)
    world_z = np.array([0.0, 0.0, 1.0], dtype=np.float64)

    delta_to_target = target_center - current_hook_position
    horizontal_approach = np.cross(world_z, target_axis)
    if float(np.linalg.norm(horizontal_approach)) > 1e-8:
        approach_axis = normalize(horizontal_approach)
        if float(np.dot(approach_axis, delta_to_target)) < 0.0:
            approach_axis = -approach_axis
    else:
        approach_axis = delta_to_target.copy()
        approach_axis[2] = 0.0
        if float(np.linalg.norm(approach_axis)) < 1e-8:
            approach_axis = delta_to_target
        approach_axis -= target_axis * float(np.dot(approach_axis, target_axis))
        approach_axis = normalize(approach_axis)

    y_axis = np.cross(world_z, approach_axis)
    if float(np.linalg.norm(y_axis)) < 1e-8:
        y_axis = reference_R[:, 1] - approach_axis * float(
            np.dot(reference_R[:, 1], approach_axis)
        )
    y_axis = normalize(y_axis)
    candidates: list[np.ndarray] = []
    for sign in (1.0, -1.0):
        candidate_y = sign * y_axis
        candidate_x = normalize(np.cross(candidate_y, approach_axis))
        candidates.append(np.stack([candidate_x, candidate_y, approach_axis], axis=1))
    return min(
        candidates,
        key=lambda frame: float(Rotation.from_matrix(frame @ reference_R.T).magnitude()),
    )


def finger_top_target(
    finger_center: np.ndarray,
    finger_axis: np.ndarray,
    surface_offset_m: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Offset from a finger center toward its world-up radial surface."""

    finger_axis = normalize(finger_axis)
    world_up = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    top_direction = world_up - finger_axis * float(np.dot(world_up, finger_axis))
    top_direction = normalize(top_direction)
    return finger_center + surface_offset_m * top_direction, top_direction


def handoff_roll_candidates(
    base_R: np.ndarray,
    preferred_roll_deg: float | None = None,
) -> list[tuple[float, np.ndarray]]:
    """Enumerate roll about the fixed handoff approach axis, smallest changes first."""

    approach_axis = base_R[:, 2]
    angles_deg = [0]
    for angle in range(15, 181, 15):
        angles_deg.extend((angle, -angle))
    candidates = [
        (
            float(angle_deg),
            Rotation.from_rotvec(approach_axis * np.deg2rad(angle_deg)).as_matrix() @ base_R,
        )
        for angle_deg in angles_deg
    ]
    if preferred_roll_deg is not None:
        candidates.sort(key=lambda item: (abs(item[0] - preferred_roll_deg) > 1e-9, abs(item[0])))
    return candidates


@dataclass(frozen=True)
class HookHandoffPlan:
    handoff_R: np.ndarray
    approach_axis: np.ndarray
    roll_deg: float
    failures: tuple[str, ...]
    pre_hook_point: np.ndarray
    pre_tcp_point: np.ndarray
    final_tcp_point: np.ndarray
    pre_path: np.ndarray
    insert_path: np.ndarray
    pre_cost: float
    insert_cost: float


def plan_hook_handoff(
    planner: PlanningModel,
    group: JointGroup,
    template: np.ndarray,
    lift_point: np.ndarray,
    grasp_R: np.ndarray,
    q_lift: np.ndarray,
    physical_target_center: np.ndarray,
    desired_hook_target: np.ndarray,
    target_axis: np.ndarray,
    hook_offset_tcp_local: np.ndarray,
    tcp_offset_local: np.ndarray,
    collision_policy: CollisionPolicy,
    preferred_roll_deg: float | None = None,
) -> HookHandoffPlan:
    current_hook_position = lift_point + grasp_R @ hook_offset_tcp_local
    base_handoff_R = target_handoff_frame(
        target_axis,
        physical_target_center,
        current_hook_position,
        grasp_R,
    )
    approach_axis = base_handoff_R[:, 2].copy()
    failures: list[str] = []
    roll_options = handoff_roll_candidates(
        base_handoff_R,
        preferred_roll_deg,
    )
    for candidate_roll_deg, handoff_R in roll_options:
        if abs(candidate_roll_deg) > MAX_HANDOFF_ROLL_DEG:
            failures.append(
                f"{candidate_roll_deg:+.0f}deg: roll exceeds "
                f"physical handoff limit ({MAX_HANDOFF_ROLL_DEG:.0f}deg)"
            )
            continue
        local_y_world_z = float(handoff_R[2, 1])
        if abs(local_y_world_z) > HANDOFF_LOCAL_Y_WORLD_Z_TOLERANCE:
            failures.append(
                f"{candidate_roll_deg:+.0f}deg: local Y not horizontal "
                f"(world_z_dot={local_y_world_z:.3f})"
            )
            continue
        pre_hook_point = desired_hook_target - HANDOFF_STANDOFF_M * approach_axis
        pre_tcp_point = pre_hook_point - handoff_R @ hook_offset_tcp_local
        final_tcp_point = desired_hook_target - handoff_R @ hook_offset_tcp_local
        try:
            pre_path, pre_cost = plan_cartesian_tcp_pose_path(
                planner,
                group,
                template,
                "piper_original/link6",
                lift_point,
                pre_tcp_point,
                grasp_R,
                handoff_R,
                tcp_offset_local,
                q_lift,
                collision_policy,
                max_tcp_step=0.015,
                max_tcp_error=0.08,
            )
            insert_path, insert_cost = plan_cartesian_tcp_path(
                planner,
                group,
                template,
                "piper_original/link6",
                pre_tcp_point,
                final_tcp_point,
                handoff_R,
                tcp_offset_local,
                pre_path[-1],
                collision_policy,
                max_tcp_step=0.005,
                max_tcp_error=0.04,
            )
            qpos_final = make_qpos_from_arm(planner, group, template, insert_path[-1])
            planner.forward(qpos_final)
            link6_id = planner.body_id("piper_original/link6")
            link6_R = planner.data.xmat[link6_id].reshape(3, 3).copy()
            tcp_world = planner.data.xpos[link6_id].copy() + link6_R @ tcp_offset_local
            predicted_hook = tcp_world + link6_R @ hook_offset_tcp_local
            hook_error = float(np.linalg.norm(predicted_hook - desired_hook_target))
            if hook_error > 0.04:
                raise RuntimeError(
                    "Final FK hook target mismatch after IK path "
                    f"(error={hook_error:.4f}m, predicted={predicted_hook.tolist()}, "
                    f"target={desired_hook_target.tolist()})"
                )
        except RuntimeError as exc:
            failures.append(f"{candidate_roll_deg:+.0f}deg: {exc}")
            continue
        return HookHandoffPlan(
            handoff_R=handoff_R,
            approach_axis=approach_axis,
            roll_deg=candidate_roll_deg,
            failures=tuple(failures),
            pre_hook_point=pre_hook_point,
            pre_tcp_point=pre_tcp_point,
            final_tcp_point=final_tcp_point,
            pre_path=pre_path,
            insert_path=insert_path,
            pre_cost=pre_cost,
            insert_cost=insert_cost,
        )
    details = "\n".join(failures)
    raise RuntimeError(f"No collision-free hook handoff pose found:\n{details}")


def append_arm_command_path(
    planner: PlanningModel,
    group: JointGroup,
    q_path: np.ndarray,
    q_commands: list[np.ndarray],
    gripper_commands: list[float],
    labels: list[str],
    label: str,
    *,
    gripper_opening: float,
) -> None:
    q_path = np.asarray(q_path, dtype=np.float64)
    if q_commands:
        previous_q = q_commands[-1]
        if len(q_path) == 0:
            q_path = np.asarray([previous_q], dtype=np.float64)
        elif float(np.linalg.norm(q_path[0] - previous_q)) > 1e-9:
            q_path = np.vstack([previous_q, q_path])
    dense = interpolate_path(q_path)
    for q in dense:
        if q_commands and float(np.linalg.norm(q - q_commands[-1])) < 1e-10:
            continue
        q_commands.append(np.asarray(q, dtype=np.float64).copy())
        gripper_commands.append(float(gripper_opening))
        labels.append(label)


def ctrl_from_command(planner: PlanningModel, group: JointGroup, q: np.ndarray, gripper_opening: float) -> np.ndarray:
    ctrl = np.zeros(planner.model.nu, dtype=np.float64)
    set_ctrl_for_q(planner, ctrl, group, q)
    gripper_act = actuator_index(planner.model, "piper_original/gripper")
    if gripper_act is not None:
        ctrl[gripper_act] = float(np.clip(gripper_opening, 0.0, 0.035))
    return ctrl


def robot_only_gravity_compensation(model, robot_prefixes: tuple[str, ...]) -> None:
    for body_id in range(1, model.nbody):
        name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body_id) or ""
        if any(name == prefix or name.startswith(f"{prefix}/") for prefix in robot_prefixes):
            model.body_gravcomp[body_id] = 1.0
        else:
            model.body_gravcomp[body_id] = 0.0


def tune_grasp_dynamics(model) -> None:
    """Tune contact/actuator parameters for a dynamic gripper grasp rollout."""

    arm_gains = (
        (160.0, 12.0, 180.0),
        (180.0, 14.0, 220.0),
        (180.0, 14.0, 220.0),
        (130.0, 10.0, 180.0),
        (90.0, 8.0, 140.0),
        (90.0, 8.0, 140.0),
    )
    for robot_prefix in ("piper_original", "piper_aerohand"):
        for joint_index, (kp, kv, force) in enumerate(arm_gains, start=1):
            aid = actuator_index(model, f"{robot_prefix}/joint{joint_index}")
            if aid is None:
                continue
            model.actuator_forcerange[aid] = [-force, force]
            model.actuator_gainprm[aid, 0] = kp
            model.actuator_biasprm[aid, 1] = -kp
            model.actuator_biasprm[aid, 2] = -kv

    gripper_act = actuator_index(model, "piper_original/gripper")
    if gripper_act is not None:
        model.actuator_forcerange[gripper_act] = [-80.0, 80.0]
        model.actuator_gainprm[gripper_act, 0] = 220.0
        model.actuator_biasprm[gripper_act, 1] = -220.0
        model.actuator_biasprm[gripper_act, 2] = -12.0

    for geom_id in range(model.ngeom):
        body_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, int(model.geom_bodyid[geom_id])) or ""
        if body_name.startswith(("piper_original/link7", "piper_original/link8", "pipette_0")):
            model.geom_friction[geom_id] = [3.0, 0.08, 0.02]
            model.geom_condim[geom_id] = 6


def palm_grasp_joints(model) -> list[tuple[str, int, float]]:
    """Return non-thumb grasp joints with targets just inside their hard limits."""

    joints: list[tuple[str, int, float]] = []
    for finger_name in PALM_GRASP_FINGERS:
        for joint_suffix in ("mcp_flex", "pip", "dip"):
            joint_name = f"piper_aerohand/right_{finger_name}_{joint_suffix}"
            joint_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, joint_name)
            if joint_id < 0:
                raise ValueError(f"Missing palm grasp joint {joint_name!r}")
            upper_limit = float(model.jnt_range[joint_id, 1])
            target = upper_limit - PALM_CLOSE_LIMIT_MARGIN_RAD
            joints.append((joint_name, int(joint_id), target))
    return joints


def apply_palm_four_finger_grasp(model, data, grasp_joints: list[tuple[str, int, float]]) -> None:
    """Close four fingers toward their limits; the thumb remains uncontrolled."""

    for _joint_name, joint_id, target in grasp_joints:
        qpos_id = int(model.jnt_qposadr[joint_id])
        dof_id = int(model.jnt_dofadr[joint_id])
        torque = (
            PALM_GRASP_KP * (target - data.qpos[qpos_id])
            - PALM_GRASP_KD * data.qvel[dof_id]
        )
        data.qfrc_applied[dof_id] += float(
            np.clip(torque, -PALM_GRASP_MAX_TORQUE, PALM_GRASP_MAX_TORQUE)
        )


def hook_handoff_success_flags(
    *,
    final_hook_target_error: float,
    final_hook_top_offset: float,
    final_hook_axis_offset: float,
    target_top_offset: float,
    target_contact_during_settle: bool,
    release_target_contact_fraction: float,
) -> tuple[bool, bool, bool, bool]:
    hook_geometrically_reached = (
        final_hook_target_error < HANDOFF_HOOK_TARGET_TOLERANCE_M
        and abs(final_hook_top_offset - target_top_offset) < HANDOFF_TOP_TOLERANCE_M
        and abs(final_hook_axis_offset) < HANDOFF_AXIS_TOLERANCE_M
    )
    hook_contact_confirmed = bool(
        target_contact_during_settle or release_target_contact_fraction > 0.5
    )
    hook_functionally_reached = (
        hook_contact_confirmed
        and final_hook_target_error < HANDOFF_HOOK_TARGET_TOLERANCE_M
        and abs(final_hook_axis_offset) < HANDOFF_AXIS_TOLERANCE_M
        and abs(final_hook_top_offset - target_top_offset) < HANDOFF_CONTACT_TOP_TOLERANCE_M
    )
    return (
        bool(hook_geometrically_reached),
        hook_contact_confirmed,
        bool(hook_functionally_reached),
        bool((hook_geometrically_reached and hook_contact_confirmed) or hook_functionally_reached),
    )


def simulate_pickup_prefix(
    planner: PlanningModel,
    group: JointGroup,
    initial_qpos: np.ndarray,
    q_commands: list[np.ndarray],
    gripper_commands: list[float],
    labels: list[str],
    tcp_offset_local: np.ndarray,
    hook_reference_local: np.ndarray,
    *,
    settle_steps: int = 20,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    CarriedPayloadState,
    dict[str, object],
]:
    """Run pickup/lift dynamics and measure payload offsets in TCP local frame."""

    model = planner.model
    data = mujoco.MjData(model)
    robot_only_gravity_compensation(model, ("piper_original", "piper_aerohand"))
    tune_grasp_dynamics(model)
    data.qpos[:] = initial_qpos
    data.ctrl[:] = 0.0
    mujoco.mj_forward(model, data)
    pipette_body = planner.body_id("pipette_0/pipette")
    initial_pipette_z = float(data.xpos[pipette_body, 2])
    qpos_frames: list[np.ndarray] = []
    ctrl_frames: list[np.ndarray] = []
    frame_labels: list[str] = []

    def record_frame(label: str, ctrl: np.ndarray) -> None:
        qpos_frames.append(data.qpos.copy())
        ctrl_frames.append(ctrl.copy())
        frame_labels.append(label)

    initial_ctrl = ctrl_from_command(
        planner,
        group,
        planner.get_joint_group(initial_qpos, group),
        0.0,
    )
    for _ in range(30):
        record_frame("scene_initial", initial_ctrl)

    for q, gripper_opening, _label in zip(q_commands, gripper_commands, labels, strict=True):
        ctrl = ctrl_from_command(planner, group, q, gripper_opening)
        data.ctrl[:] = ctrl
        for _ in range(settle_steps):
            data.qfrc_applied[:] = 0.0
            mujoco.mj_step(model, data)
            record_frame(_label, ctrl)

    planner.forward(data.qpos.copy())
    payload_state = measure_carried_payload_state(
        planner,
        link_body="piper_original/link6",
        tcp_offset_local=tcp_offset_local,
        payload_body="pipette_0",
        hook_body="pipette_0/pipette",
        hook_reference_local=hook_reference_local,
    )
    pipette_z = float(planner.data.xpos[pipette_body, 2])
    return (
        np.asarray(qpos_frames, dtype=np.float64),
        np.asarray(ctrl_frames, dtype=np.float64),
        np.asarray(frame_labels),
        data.qvel.copy(),
        payload_state,
        {
            "initial_pipette_z": initial_pipette_z,
            "post_pickup_pipette_z": pipette_z,
            "pickup_lifted": bool(
                pipette_z > initial_pipette_z + max(0.01, 0.5 * LIFT_CLEARANCE_M)
            ),
        },
    )

def simulate_commands(
    planner: PlanningModel,
    group: JointGroup,
    initial_qpos: np.ndarray,
    q_commands: list[np.ndarray],
    gripper_commands: list[float],
    labels: list[str],
    tcp_offset_local: np.ndarray,
    grasp_site_offset_m: float,
    commanded_lift_m: float,
    hook_reference_local: np.ndarray,
    handoff_target_site: str,
    handoff_target_body: str,
    handoff_target_axis_local: np.ndarray,
    handoff_target_surface_offset_m: float,
    handoff_target_vertical_offset_m: float,
    *,
    settle_steps: int = 20,
    hold_initial_frames: int = 30,
    initial_qvel: np.ndarray | None = None,
    lift_already_verified: bool = False,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, float | bool]]:
    model = planner.model
    data = mujoco.MjData(model)
    robot_only_gravity_compensation(model, ("piper_original", "piper_aerohand"))
    tune_grasp_dynamics(model)
    data.qpos[:] = initial_qpos
    if initial_qvel is not None:
        data.qvel[:] = initial_qvel
    data.ctrl[:] = 0.0
    mujoco.mj_forward(model, data)
    pipette_body = planner.body_id("pipette_0/pipette")
    link6_body = planner.body_id("piper_original/link6")
    handoff_target_body_id = planner.body_id(handoff_target_body)
    handoff_target_site_id = mujoco.mj_name2id(
        model,
        mujoco.mjtObj.mjOBJ_SITE,
        handoff_target_site,
    )
    if handoff_target_site_id < 0:
        raise ValueError(f"Missing site {handoff_target_site!r}")
    initial_pipette_z = float(data.xpos[pipette_body, 2])
    grasp_joints = palm_grasp_joints(model)

    qpos_frames: list[np.ndarray] = []
    ctrl_frames: list[np.ndarray] = []
    frame_labels: list[str] = []
    pipette_z_frames: list[float] = []
    grasp_site_error_frames: list[float] = []
    finger_contact_count_frames: list[int] = []
    rack_contact_frames: list[bool] = []
    hook_target_error_frames: list[float] = []
    hook_position_frames: list[np.ndarray] = []
    target_point_frames: list[np.ndarray] = []
    handoff_axis_dot_frames: list[float] = []
    link6_local_y_world_z_frames: list[float] = []
    hook_top_offset_frames: list[float] = []
    hook_axis_offset_frames: list[float] = []
    target_contact_frames: list[bool] = []
    table_contact_frames: list[bool] = []
    palm_contact_count_frames: list[int] = []
    palm_tip_contact_count_frames: list[int] = []
    palm_contacted_finger_frames: list[frozenset[str]] = []
    palm_tip_contacted_finger_frames: list[frozenset[str]] = []

    def record_frame(label: str, ctrl: np.ndarray) -> None:
        qpos_frames.append(data.qpos.copy())
        ctrl_frames.append(ctrl.copy())
        frame_labels.append(label)
        pipette_R = data.xmat[pipette_body].reshape(3, 3)
        link6_R = data.xmat[link6_body].reshape(3, 3)
        grasp_site = data.xpos[pipette_body] + pipette_R @ np.array(
            [0.0, 0.0, grasp_site_offset_m],
            dtype=np.float64,
        )
        gripper_center = data.xpos[link6_body] + link6_R @ tcp_offset_local
        pipette_z_frames.append(float(data.xpos[pipette_body, 2]))
        grasp_site_error_frames.append(float(np.linalg.norm(gripper_center - grasp_site)))
        hook_position = data.xpos[pipette_body] + pipette_R @ hook_reference_local
        target_center = data.site_xpos[handoff_target_site_id]
        target_axis = (
            data.xmat[handoff_target_body_id].reshape(3, 3) @ handoff_target_axis_local
        )
        target_point, top_direction = finger_top_target(
            target_center,
            target_axis,
            handoff_target_surface_offset_m,
        )
        target_point = target_point + np.array(
            [0.0, 0.0, handoff_target_vertical_offset_m],
            dtype=np.float64,
        )
        hook_position_frames.append(hook_position.copy())
        target_point_frames.append(target_point.copy())
        hook_from_center = hook_position - target_center
        hook_target_error_frames.append(float(np.linalg.norm(hook_position - target_point)))
        handoff_axis_dot_frames.append(float(np.dot(link6_R[:, 2], normalize(target_axis))))
        link6_local_y_world_z_frames.append(float(link6_R[2, 1]))
        hook_top_offset_frames.append(float(np.dot(hook_from_center, top_direction)))
        hook_axis_offset_frames.append(float(np.dot(hook_from_center, normalize(target_axis))))

        contacting_fingers: set[str] = set()
        pipette_rack_contact = False
        pipette_target_contact = False
        pipette_table_contact = False
        palm_contacted_fingers: set[str] = set()
        palm_tip_contacted_fingers: set[str] = set()
        for contact_index in range(data.ncon):
            contact = data.contact[contact_index]
            geom_names = {
                mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, int(contact.geom1)) or "",
                mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, int(contact.geom2)) or "",
            }
            body_names = {
                mujoco.mj_id2name(
                    model,
                    mujoco.mjtObj.mjOBJ_BODY,
                    int(model.geom_bodyid[contact.geom1]),
                )
                or "",
                mujoco.mj_id2name(
                    model,
                    mujoco.mjtObj.mjOBJ_BODY,
                    int(model.geom_bodyid[contact.geom2]),
                )
                or "",
            }
            if not any(name.startswith("pipette_0/") for name in body_names):
                continue
            if any(name.startswith("pipette_rack_0/") for name in body_names):
                pipette_rack_contact = True
            if any(name.startswith("table_0/") for name in body_names):
                pipette_table_contact = True
            if handoff_target_body in body_names:
                pipette_target_contact = True
            for finger_name in PALM_GRASP_FINGERS:
                if any(
                    name.startswith(f"piper_aerohand/right_{finger_name}_")
                    for name in body_names
                ):
                    palm_contacted_fingers.add(finger_name)
                tip_name = PALM_TIP_GEOMS[finger_name]
                if any(name == tip_name or name.endswith(f"/{tip_name}") for name in geom_names):
                    palm_tip_contacted_fingers.add(finger_name)
            for finger_name in ("piper_original/link7", "piper_original/link8"):
                if finger_name in body_names:
                    contacting_fingers.add(finger_name)
        finger_contact_count_frames.append(len(contacting_fingers))
        rack_contact_frames.append(pipette_rack_contact)
        target_contact_frames.append(pipette_target_contact)
        table_contact_frames.append(pipette_table_contact)
        palm_contact_count_frames.append(len(palm_contacted_fingers))
        palm_tip_contact_count_frames.append(len(palm_tip_contacted_fingers))
        palm_contacted_finger_frames.append(frozenset(palm_contacted_fingers))
        palm_tip_contacted_finger_frames.append(frozenset(palm_tip_contacted_fingers))

    initial_ctrl = ctrl_from_command(planner, group, planner.get_joint_group(initial_qpos, group), 0.0)
    for _ in range(hold_initial_frames):
        record_frame("scene_initial", initial_ctrl)

    palm_close_steps = 0
    palm_close_stop_reason = "not_run"
    for q, gripper_opening, label in zip(q_commands, gripper_commands, labels, strict=True):
        ctrl = ctrl_from_command(planner, group, q, gripper_opening)
        data.ctrl[:] = ctrl
        step_count = settle_steps
        if label == "palm_close":
            step_count = PALM_CLOSE_MAX_STEPS
        for _ in range(step_count):
            data.qfrc_applied[:] = 0.0
            if label == "palm_close":
                apply_palm_four_finger_grasp(model, data, grasp_joints)
            mujoco.mj_step(model, data)
            record_frame(label, ctrl)
            if label != "palm_close":
                continue
            palm_close_steps += 1
            if palm_close_steps < PALM_CLOSE_MIN_STEPS:
                continue
            joint_states = [
                (
                    float(data.qpos[int(model.jnt_qposadr[joint_id])]),
                    abs(float(data.qvel[int(model.jnt_dofadr[joint_id])])),
                    target,
                )
                for _name, joint_id, target in grasp_joints
            ]
            reached_limit = [
                qpos >= target - PALM_CLOSE_LIMIT_TOLERANCE_RAD
                for qpos, _speed, target in joint_states
            ]
            stalled = [
                speed <= PALM_CLOSE_STOP_SPEED_RAD_S
                for _qpos, speed, _target in joint_states
            ]
            if all(at_limit or stopped for at_limit, stopped in zip(reached_limit, stalled, strict=True)):
                palm_close_stop_reason = "all_joints_limit_or_stalled"
                break
        else:
            if label == "palm_close":
                palm_close_stop_reason = "maximum_duration"

    frame_labels_array = np.asarray(frame_labels)
    pipette_z_array = np.asarray(pipette_z_frames, dtype=np.float64)
    grasp_site_error_array = np.asarray(grasp_site_error_frames, dtype=np.float64)
    finger_contact_count_array = np.asarray(finger_contact_count_frames, dtype=np.int8)
    rack_contact_array = np.asarray(rack_contact_frames, dtype=bool)
    table_contact_array = np.asarray(table_contact_frames, dtype=bool)
    hook_target_error_array = np.asarray(hook_target_error_frames, dtype=np.float64)
    hook_position_array = np.asarray(hook_position_frames, dtype=np.float64)
    target_point_array = np.asarray(target_point_frames, dtype=np.float64)
    handoff_axis_dot_array = np.asarray(handoff_axis_dot_frames, dtype=np.float64)
    link6_local_y_world_z_array = np.asarray(link6_local_y_world_z_frames, dtype=np.float64)
    hook_top_offset_array = np.asarray(hook_top_offset_frames, dtype=np.float64)
    hook_axis_offset_array = np.asarray(hook_axis_offset_frames, dtype=np.float64)
    target_contact_array = np.asarray(target_contact_frames, dtype=bool)
    palm_contact_count_array = np.asarray(palm_contact_count_frames, dtype=np.int8)
    palm_tip_contact_count_array = np.asarray(palm_tip_contact_count_frames, dtype=np.int8)
    carry_mask = np.isin(
        frame_labels_array,
        ("lift", "post_pickup", "pre_handoff", "hook_insert", "hook_settle"),
    )
    handoff_mask = np.isin(
        frame_labels_array,
        ("pre_handoff", "hook_insert", "hook_settle"),
    )
    handoff_motion_mask = np.isin(
        frame_labels_array,
        ("post_pickup", "pre_handoff", "hook_insert", "hook_settle", "retreat"),
    )
    max_pipette_z = float(np.max(pipette_z_array))
    required_lift_m = max(0.01, 0.5 * commanded_lift_m)
    pipette_lifted = bool(
        lift_already_verified or max_pipette_z > initial_pipette_z + required_lift_m
    )
    max_carry_grasp_site_error = float(np.max(grasp_site_error_array[carry_mask]))
    handoff_end_mask = frame_labels_array == "hook_settle"
    retreat_mask = frame_labels_array == "retreat"
    palm_close_mask = frame_labels_array == "palm_close"
    final_carry_index = int(np.flatnonzero(handoff_end_mask)[-1])
    final_grasp_site_error = float(grasp_site_error_array[final_carry_index])
    final_two_finger_contact = bool(finger_contact_count_array[final_carry_index] == 2)
    carry_two_finger_contact_fraction = float(
        np.mean(finger_contact_count_array[carry_mask] == 2)
    )
    final_rack_contact = bool(rack_contact_array[final_carry_index])
    handoff_rack_contact_fraction = float(np.mean(rack_contact_array[handoff_mask]))
    final_hook_target_error = float(hook_target_error_array[final_carry_index])
    final_hook_position = hook_position_array[final_carry_index]
    final_target_position = target_point_array[final_carry_index]
    final_hook_target_error_world = final_hook_position - final_target_position
    final_handoff_axis_dot = float(handoff_axis_dot_array[final_carry_index])
    final_link6_local_y_world_z = float(link6_local_y_world_z_array[final_carry_index])
    max_abs_handoff_local_y_world_z = float(
        np.max(np.abs(link6_local_y_world_z_array[handoff_motion_mask]))
    )
    final_hook_top_offset = float(hook_top_offset_array[final_carry_index])
    final_hook_axis_offset = float(hook_axis_offset_array[final_carry_index])
    target_contact_during_settle = bool(
        np.any(target_contact_array[frame_labels_array == "hook_settle"])
    )
    grasp_retained = (
        pipette_lifted
        and max_carry_grasp_site_error < 0.025
        and final_grasp_site_error < 0.025
        and not final_rack_contact
    )
    release_target_contact_fraction = float(np.mean(target_contact_array[retreat_mask]))
    release_finger_contact_fraction = float(
        np.mean(finger_contact_count_array[retreat_mask] > 0)
    )
    release_table_contact_fraction = float(np.mean(table_contact_array[retreat_mask]))
    release_rack_contact_fraction = float(np.mean(rack_contact_array[retreat_mask]))
    release_survived = (
        release_target_contact_fraction > 0.5
        and release_finger_contact_fraction == 0.0
        and release_table_contact_fraction == 0.0
        and release_rack_contact_fraction == 0.0
    )
    target_top_offset = handoff_target_surface_offset_m + handoff_target_vertical_offset_m
    (
        hook_geometrically_reached,
        hook_contact_confirmed,
        hook_functionally_reached,
        hook_handoff_reached,
    ) = hook_handoff_success_flags(
        final_hook_target_error=final_hook_target_error,
        final_hook_top_offset=final_hook_top_offset,
        final_hook_axis_offset=final_hook_axis_offset,
        target_top_offset=target_top_offset,
        target_contact_during_settle=target_contact_during_settle,
        release_target_contact_fraction=release_target_contact_fraction,
    )
    palm_grasp_max_contact_count = int(np.max(palm_contact_count_array[palm_close_mask]))
    palm_grasp_final_contact_count = int(palm_contact_count_array[-1])
    palm_tip_max_contact_count = int(np.max(palm_tip_contact_count_array[palm_close_mask]))
    palm_tip_final_contact_count = int(palm_tip_contact_count_array[-1])
    palm_four_finger_grasped = palm_grasp_max_contact_count >= len(PALM_GRASP_FINGERS)
    palm_grasp_stable = (
        palm_tip_max_contact_count >= 2
        and palm_tip_final_contact_count >= 2
        and not bool(np.any(table_contact_array[palm_close_mask]))
        and not bool(np.any(rack_contact_array[palm_close_mask]))
        and not bool(np.any(finger_contact_count_array[palm_close_mask] > 0))
    )
    palm_close_joint_states = {}
    for joint_name, joint_id, target in grasp_joints:
        qpos_id = int(model.jnt_qposadr[joint_id])
        dof_id = int(model.jnt_dofadr[joint_id])
        qpos = float(data.qpos[qpos_id])
        speed = abs(float(data.qvel[dof_id]))
        at_limit = qpos >= target - PALM_CLOSE_LIMIT_TOLERANCE_RAD
        finger_name = joint_name.removeprefix("piper_aerohand/right_").split("_", 1)[0]
        chain_contacted = any(
            finger_name in contacts
            for contacts, is_close in zip(palm_contacted_finger_frames, palm_close_mask, strict=True)
            if is_close
        )
        tip_contacted = any(
            finger_name in contacts
            for contacts, is_close in zip(palm_tip_contacted_finger_frames, palm_close_mask, strict=True)
            if is_close
        )
        if at_limit:
            stop_state = "limit"
        elif tip_contacted:
            stop_state = "stalled_with_tip_contact"
        elif chain_contacted:
            stop_state = "stalled_with_finger_link_contact"
        else:
            stop_state = "dynamics_stalled_before_limit"
        palm_close_joint_states[joint_name] = {
            "qpos_rad": qpos,
            "target_rad": target,
            "upper_limit_rad": float(model.jnt_range[joint_id, 1]),
            "speed_rad_s": speed,
            "stop_state": stop_state,
        }
    metrics = {
        "initial_pipette_z": initial_pipette_z,
        "final_pipette_z": float(pipette_z_array[-1]),
        "max_pipette_z": max_pipette_z,
        "required_lift_m": required_lift_m,
        "pipette_lifted_by_dynamics": pipette_lifted,
        "max_carry_grasp_site_error_m": max_carry_grasp_site_error,
        "final_grasp_site_error_m": final_grasp_site_error,
        "carry_two_finger_contact_fraction": carry_two_finger_contact_fraction,
        "final_two_finger_contact": final_two_finger_contact,
        "handoff_rack_contact_fraction": handoff_rack_contact_fraction,
        "final_rack_contact": final_rack_contact,
        "final_hook_target_error_m": final_hook_target_error,
        "final_hook_target_error_world": final_hook_target_error_world.tolist(),
        "final_hook_position_world": final_hook_position.tolist(),
        "final_handoff_target_position_world": final_target_position.tolist(),
        "final_handoff_axis_dot": final_handoff_axis_dot,
        "final_link6_local_y_world_z": final_link6_local_y_world_z,
        "max_abs_handoff_local_y_world_z": max_abs_handoff_local_y_world_z,
        "final_hook_top_offset_m": final_hook_top_offset,
        "final_hook_axis_offset_m": final_hook_axis_offset,
        "target_contact_during_settle": target_contact_during_settle,
        "hook_geometrically_reached": hook_geometrically_reached,
        "hook_contact_confirmed": hook_contact_confirmed,
        "hook_functionally_reached": hook_functionally_reached,
        "hook_target_tolerance_m": HANDOFF_HOOK_TARGET_TOLERANCE_M,
        "hook_top_tolerance_m": HANDOFF_TOP_TOLERANCE_M,
        "hook_contact_top_tolerance_m": HANDOFF_CONTACT_TOP_TOLERANCE_M,
        "hook_axis_tolerance_m": HANDOFF_AXIS_TOLERANCE_M,
        "hook_handoff_reached": hook_handoff_reached,
        "release_target_contact_fraction": release_target_contact_fraction,
        "release_finger_contact_fraction": release_finger_contact_fraction,
        "release_table_contact_fraction": release_table_contact_fraction,
        "release_rack_contact_fraction": release_rack_contact_fraction,
        "release_survived": release_survived,
        "palm_grasp_max_contact_count": palm_grasp_max_contact_count,
        "palm_grasp_final_contact_count": palm_grasp_final_contact_count,
        "palm_four_finger_grasped": palm_four_finger_grasped,
        "palm_tip_max_contact_count": palm_tip_max_contact_count,
        "palm_tip_final_contact_count": palm_tip_final_contact_count,
        "palm_grasp_stable": palm_grasp_stable,
        "palm_close_steps": palm_close_steps,
        "palm_close_stop_reason": palm_close_stop_reason,
        "palm_close_joints": palm_close_joint_states,
        "pipette_sustained_by_dynamics": grasp_retained,
        "dynamic_handoff_success": grasp_retained,
    }
    return (
        np.asarray(qpos_frames, dtype=np.float64),
        np.asarray(ctrl_frames, dtype=np.float64),
        np.asarray(frame_labels),
        metrics,
    )


def render_video(
    model,
    qpos_frames: np.ndarray,
    output_path: Path,
    fps: int = 30,
    width: int = 960,
    height: int = 720,
    stride: int = 5,
) -> None:
    model.vis.global_.offwidth = max(model.vis.global_.offwidth, width)
    model.vis.global_.offheight = max(model.vis.global_.offheight, height)
    renderer = mujoco.Renderer(model, width=width, height=height)
    camera = mujoco.MjvCamera()
    camera.type = mujoco.mjtCamera.mjCAMERA_FREE
    camera.fixedcamid = -1
    camera.lookat[:] = [0.0, -0.08, 1.05]
    camera.distance = 1.35
    camera.azimuth = 0.0
    camera.elevation = -30.0
    data = mujoco.MjData(model)
    writer = imageio.get_writer(
        output_path,
        fps=fps,
        codec="libx264",
        quality=8,
        macro_block_size=1,
    )
    try:
        for qpos in qpos_frames[:: max(1, int(stride))]:
            data.qpos[:] = qpos
            mujoco.mj_forward(model, data)
            renderer.update_scene(data, camera=camera)
            rgb = renderer.render()
            writer.append_data(rgb)
    finally:
        writer.close()
        renderer.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=str(DEFAULT_MODEL))
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--seed", type=int, default=11)
    parser.add_argument("--episode-spec", default=None, help="Optional JSON initial-state override generated by a task sampler.")
    parser.add_argument("--record-video", action="store_true")
    parser.add_argument("--video-stride", type=int, default=5)
    parser.add_argument("--allow-failed-grasp", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser()
    if not output_dir.is_absolute():
        output_dir = PROJECT_ROOT / output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(args.seed)
    planner = PlanningModel(str(Path(args.model).expanduser()))
    group = JointGroup.from_names(planner.model, LEFT_ARM_JOINTS)

    episode_spec = None
    if args.episode_spec is not None:
        episode_spec_path = Path(args.episode_spec).expanduser()
        if not episode_spec_path.is_absolute():
            episode_spec_path = PROJECT_ROOT / episode_spec_path
        episode_spec = load_episode_spec(episode_spec_path)

    if episode_spec is not None:
        apply_episode_spec_to_model(planner.model, episode_spec)
    qpos_scene_initial = planner.base_qpos.copy()
    if episode_spec is not None:
        apply_episode_spec_to_qpos(planner.model, qpos_scene_initial, episode_spec)
    planner.forward(qpos_scene_initial)
    qpos_open = qpos_scene_initial.copy()
    set_left_gripper(planner, qpos_open, 0.035)
    planner.forward(qpos_open)

    tcp_offset_local = gripper_center_offset_local(planner, qpos_open)
    q_start = planner.get_joint_group(qpos_open, group)

    pipette_body_id = planner.body_id("pipette_0/pipette")
    pipette_pos = planner.data.xpos[pipette_body_id].copy()
    pipette_R = planner.data.xmat[pipette_body_id].reshape(3, 3).copy()
    pipette_axis = normalize(pipette_R[:, 2])
    grip_point = pipette_pos + PIPETTE_GRASP_SITE_OFFSET_M * pipette_axis
    link6_id = planner.body_id("piper_original/link6")
    initial_link6_R = planner.data.xmat[link6_id].reshape(3, 3).copy()

    pre_policy = CollisionPolicy(
        robot_prefixes=("piper_original",),
        obstacle_prefixes=("table_0", "pipette_rack_0", "piper_aerohand"),
        margin=0.0015,
    )
    grasp_policy = CollisionPolicy(
        robot_prefixes=("piper_original",),
        obstacle_prefixes=("table_0", "pipette_rack_0", "piper_aerohand"),
        margin=0.0015,
    )
    approach_failures: list[str] = []
    grasp_orientation_delta_deg = 0.0
    for candidate_index, grasp_R in enumerate(
        level_side_grasp_frames(pipette_axis, initial_link6_R)
    ):
        grasp_approach_axis = grasp_R[:, 2].copy()
        pregrasp_point = grip_point - 0.10 * grasp_approach_axis
        try:
            q_pregrasp, grasp_R, pre_cost = find_stage_ik(
                planner,
                group,
                qpos_open,
                "piper_original/link6",
                pregrasp_point,
                grasp_R,
                pipette_axis,
                tcp_offset_local,
                q_start,
                pre_policy,
                rng,
                max_tcp_error=0.16,
            )
            rrt_pre = make_rrt(planner, group, qpos_open, pre_policy, seed=args.seed)
            pre_result = rrt_pre.plan(q_start, q_pregrasp)
            leveled_pregrasp_path = level_gripper_y_path(
                planner,
                group,
                qpos_open,
                pre_result.path,
                pre_policy,
            )
            q_pregrasp = leveled_pregrasp_path[-1]
            grasp_path, grasp_cost = plan_cartesian_tcp_path(
                planner,
                group,
                qpos_open,
                "piper_original/link6",
                pregrasp_point,
                grip_point,
                grasp_R,
                tcp_offset_local,
                q_pregrasp,
                grasp_policy,
                max_tcp_step=0.01,
                max_tcp_error=0.05,
            )
        except RuntimeError as exc:
            approach_failures.append(f"level_frame_{candidate_index}: {exc}")
            continue
        grasp_orientation_delta_deg = float(
            np.degrees(Rotation.from_matrix(grasp_R @ initial_link6_R.T).magnitude())
        )
        break
    else:
        details = "\n".join(approach_failures)
        raise RuntimeError(f"No collision-free grasp approach found:\n{details}")

    q_grasp = grasp_path[-1]

    qpos_grasp = make_qpos_from_arm(planner, group, qpos_open, q_grasp)
    set_left_gripper(planner, qpos_grasp, 0.0)
    planner.forward(qpos_grasp)

    lift_point = grip_point + np.array([0.0, 0.0, LIFT_CLEARANCE_M])
    lift_path, lift_cost = plan_cartesian_tcp_path(
        planner,
        group,
        qpos_grasp,
        "piper_original/link6",
        grip_point,
        lift_point,
        grasp_R,
        tcp_offset_local,
        q_grasp,
        grasp_policy,
        max_tcp_step=0.015,
        max_tcp_error=0.06,
    )
    q_lift = lift_path[-1]

    qpos_lift = make_qpos_from_arm(planner, group, qpos_grasp, q_lift)
    planner.forward(qpos_lift)

    hook_world_initial = pipette_pos + pipette_R @ PIPETTE_HOOK_REFERENCE_LOCAL
    payload_root_id = planner.body_id("pipette_0")
    payload_root_pos = planner.data.xpos[payload_root_id].copy()
    payload_root_R = planner.data.xmat[payload_root_id].reshape(3, 3).copy()
    ideal_payload_offset_tcp_local = grasp_R.T @ (payload_root_pos - grip_point)
    ideal_payload_R_tcp = grasp_R.T @ payload_root_R
    ideal_hook_offset_tcp_local = grasp_R.T @ (hook_world_initial - grip_point)
    payload_offset_tcp_local = ideal_payload_offset_tcp_local.copy()
    payload_R_tcp = ideal_payload_R_tcp.copy()
    hook_offset_tcp_local = ideal_hook_offset_tcp_local.copy()
    target_body_id = planner.body_id(HANDOFF_TARGET_BODY)
    target_center = site_world_position(planner, HANDOFF_TARGET_SITE)
    target_body_R = planner.data.xmat[target_body_id].reshape(3, 3).copy()
    target_axis = normalize(target_body_R @ HANDOFF_TARGET_AXIS_LOCAL)
    handoff_target_point, handoff_top_direction = finger_top_target(
        target_center,
        target_axis,
        HANDOFF_TARGET_SURFACE_OFFSET_M,
    )
    handoff_target_point += np.array(
        [0.0, 0.0, HANDOFF_TARGET_VERTICAL_OFFSET_M],
        dtype=np.float64,
    )

    q_commands: list[np.ndarray] = []
    gripper_commands: list[float] = []
    labels: list[str] = []
    q_commands.append(q_start.copy())
    gripper_commands.append(0.035)
    labels.append("open")
    append_arm_command_path(
        planner,
        group,
        leveled_pregrasp_path,
        q_commands,
        gripper_commands,
        labels,
        "pregrasp",
        gripper_opening=0.035,
    )
    append_arm_command_path(
        planner,
        group,
        grasp_path,
        q_commands,
        gripper_commands,
        labels,
        "grasp",
        gripper_opening=0.035,
    )
    for opening in np.linspace(0.035, 0.0, 18):
        q_commands.append(q_grasp.copy())
        gripper_commands.append(float(opening))
        labels.append("close")
    append_arm_command_path(
        planner,
        group,
        lift_path,
        q_commands,
        gripper_commands,
        labels,
        "lift",
        gripper_opening=0.0,
    )
    pickup_q_commands = [value.copy() for value in q_commands]
    pickup_gripper_commands = list(gripper_commands)
    pickup_labels = list(labels)

    (
        pickup_qpos_array,
        pickup_ctrl_array,
        pickup_labels_array,
        pickup_final_qvel,
        measured_pickup_payload,
        pickup_measurement,
    ) = simulate_pickup_prefix(
        planner,
        group,
        qpos_scene_initial,
        pickup_q_commands,
        pickup_gripper_commands,
        pickup_labels,
        tcp_offset_local,
        PIPETTE_HOOK_REFERENCE_LOCAL,
    )
    pickup_final_qpos = pickup_qpos_array[-1].copy()
    planner.forward(pickup_final_qpos)
    q_lift_actual = planner.get_joint_group(pickup_final_qpos, group)
    payload_offset_tcp_local = measured_pickup_payload.payload_offset_tcp_local
    payload_R_tcp = measured_pickup_payload.payload_R_tcp
    hook_offset_tcp_local = measured_pickup_payload.hook_offset_tcp_local

    target_correction = np.zeros(3, dtype=np.float64)
    correction_history: list[dict[str, object]] = []
    preferred_handoff_roll_deg: float | None = None
    best_rollout: tuple[
        float,
        np.ndarray,
        np.ndarray,
        np.ndarray,
        dict[str, object],
        HookHandoffPlan,
        np.ndarray,
        float,
        object,
    ] | None = None
    for correction_attempt in range(HANDOFF_CORRECTION_ATTEMPTS):
        desired_hook_target = handoff_target_point + target_correction
        try:
            handoff_plan = plan_hook_handoff(
                planner,
                group,
                pickup_final_qpos,
                measured_pickup_payload.tcp_world,
                measured_pickup_payload.tcp_R_world,
                q_lift_actual,
                handoff_target_point,
                desired_hook_target,
                target_axis,
                hook_offset_tcp_local,
                tcp_offset_local,
                grasp_policy,
                preferred_handoff_roll_deg,
            )
        except RuntimeError as exc:
            correction_history.append(
                {
                    "attempt": correction_attempt,
                    "target_correction_world": target_correction.tolist(),
                    "planning_error": str(exc),
                }
            )
            if best_rollout is not None:
                break
            raise
        preferred_handoff_roll_deg = handoff_plan.roll_deg
        retreat_tcp_point = (
            handoff_plan.final_tcp_point - PIPER_RETREAT_M * handoff_plan.approach_axis
        )
        retreat_path, retreat_cost = plan_cartesian_tcp_path(
            planner,
            group,
            pickup_final_qpos,
            "piper_original/link6",
            handoff_plan.final_tcp_point,
            retreat_tcp_point,
            handoff_plan.handoff_R,
            tcp_offset_local,
            handoff_plan.insert_path[-1],
            grasp_policy,
            max_tcp_step=0.01,
            max_tcp_error=0.04,
        )

        q_commands = [q_lift_actual.copy()]
        gripper_commands = [0.0]
        labels = ["post_pickup"]
        append_arm_command_path(
            planner,
            group,
            handoff_plan.pre_path,
            q_commands,
            gripper_commands,
            labels,
            "pre_handoff",
            gripper_opening=0.0,
        )
        append_arm_command_path(
            planner,
            group,
            handoff_plan.insert_path,
            q_commands,
            gripper_commands,
            labels,
            "hook_insert",
            gripper_opening=0.0,
        )
        for _ in range(HANDOFF_SETTLE_COMMANDS):
            q_commands.append(handoff_plan.insert_path[-1].copy())
            gripper_commands.append(0.0)
            labels.append("hook_settle")
        for opening in np.linspace(0.0, 0.035, RELEASE_COMMANDS):
            q_commands.append(handoff_plan.insert_path[-1].copy())
            gripper_commands.append(float(opening))
            labels.append("release")
        append_arm_command_path(
            planner,
            group,
            retreat_path,
            q_commands,
            gripper_commands,
            labels,
            "retreat",
            gripper_opening=0.035,
        )
        q_commands.append(retreat_path[-1].copy())
        gripper_commands.append(0.035)
        labels.append("palm_close")

        payload_collision_report = check_carried_payload_path(
            planner,
            group=group,
            template_qpos=pickup_final_qpos,
            q_path=q_commands,
            labels=labels,
            link_body="piper_original/link6",
            tcp_offset_local=tcp_offset_local,
            payload_freejoint="pipette_0_free",
            payload_prefixes=("pipette_0",),
            obstacle_prefixes=("table_0", "pipette_rack_0"),
            payload_offset_tcp_local=payload_offset_tcp_local,
            payload_R_tcp=payload_R_tcp,
            carry_labels=("pre_handoff", "hook_insert", "hook_settle"),
        )
        if not payload_collision_report.ok:
            if not args.allow_failed_grasp:
                raise RuntimeError(
                    "Kinematic carried-payload collision check failed: "
                    + json.dumps(payload_collision_report.as_json(), indent=2)
                )
            print(
                "WARNING: Kinematic carried-payload collision check failed; "
                "continuing because --allow-failed-grasp is set."
            )

        handoff_qpos_array, handoff_ctrl_array, handoff_labels_array, dynamics_metrics = simulate_commands(
            planner,
            group,
            pickup_final_qpos,
            q_commands,
            gripper_commands,
            labels,
            tcp_offset_local,
            PIPETTE_GRASP_SITE_OFFSET_M,
            LIFT_CLEARANCE_M,
            PIPETTE_HOOK_REFERENCE_LOCAL,
            HANDOFF_TARGET_SITE,
            HANDOFF_TARGET_BODY,
            HANDOFF_TARGET_AXIS_LOCAL,
            HANDOFF_TARGET_SURFACE_OFFSET_M,
            HANDOFF_TARGET_VERTICAL_OFFSET_M,
            initial_qvel=pickup_final_qvel,
            hold_initial_frames=0,
            lift_already_verified=bool(pickup_measurement["pickup_lifted"]),
        )
        qpos_array = np.concatenate([pickup_qpos_array, handoff_qpos_array], axis=0)
        ctrl_array = np.concatenate([pickup_ctrl_array, handoff_ctrl_array], axis=0)
        labels_array = np.concatenate([pickup_labels_array, handoff_labels_array], axis=0)
        correction_history.append(
            {
                "attempt": correction_attempt,
                "target_correction_world": target_correction.tolist(),
                "hook_error_world": dynamics_metrics["final_hook_target_error_world"],
                "hook_error_m": dynamics_metrics["final_hook_target_error_m"],
                "roll_deg": handoff_plan.roll_deg,
            }
        )
        rollout_score = float(dynamics_metrics["final_hook_target_error_m"])
        if (args.allow_failed_grasp or dynamics_metrics["pipette_sustained_by_dynamics"]) and (
            best_rollout is None or rollout_score < best_rollout[0]
        ):
            best_rollout = (
                rollout_score,
                qpos_array.copy(),
                ctrl_array.copy(),
                labels_array.copy(),
                dict(dynamics_metrics),
                handoff_plan,
                target_correction.copy(),
                retreat_cost,
                payload_collision_report,
            )
        if dynamics_metrics["hook_handoff_reached"]:
            break
        if correction_attempt + 1 < HANDOFF_CORRECTION_ATTEMPTS:
            target_correction -= HANDOFF_CORRECTION_GAIN * np.asarray(
                dynamics_metrics["final_hook_target_error_world"],
                dtype=np.float64,
            )
    if not dynamics_metrics["hook_handoff_reached"] and best_rollout is not None:
        (
            _,
            qpos_array,
            ctrl_array,
            labels_array,
            dynamics_metrics,
            handoff_plan,
            target_correction,
            retreat_cost,
            payload_collision_report,
        ) = best_rollout
    task_success = bool(
        dynamics_metrics["dynamic_handoff_success"]
        and dynamics_metrics["hook_handoff_reached"]
        and dynamics_metrics["release_survived"]
        and dynamics_metrics["palm_grasp_stable"]
    )
    if not task_success and not args.allow_failed_grasp:
        print(json.dumps(dynamics_metrics, indent=2))
        raise RuntimeError(
            "Dynamic handoff failed: grasp retention, hook placement, released hang, or stable fingertip-supported palm grasp did not pass. "
            "Use --allow-failed-grasp to export the failed rollout for inspection."
        )
    npz_path = output_dir / "piper_gripper_pipette_handoff_expert.npz"
    np.savez_compressed(
        npz_path,
        qpos=qpos_array,
        ctrl=ctrl_array,
        labels=labels_array,
        model=str(Path(args.model)),
    )

    summary = {
        "model": str(Path(args.model)),
        "episode_spec": episode_spec.as_json() if episode_spec is not None else None,
        "trajectory": str(npz_path),
        "frames": int(qpos_array.shape[0]),
        "pregrasp_cost": pre_cost,
        "grasp_cost": grasp_cost,
        "lift_cost": lift_cost,
        "pre_handoff_cost": handoff_plan.pre_cost,
        "hook_insert_cost": handoff_plan.insert_cost,
        "retreat_cost": retreat_cost,
        "tcp_offset_local": tcp_offset_local.tolist(),
        "pipette_axis_world_initial": pipette_axis.tolist(),
        "grasp_approach_axis_world_initial": grasp_approach_axis.tolist(),
        "grasp_orientation_delta_deg": grasp_orientation_delta_deg,
        "grasp_local_y_world_z": float(grasp_R[2, 1]),
        "grasp_approach_failures": approach_failures,
        "grasp_site_offset_m": PIPETTE_GRASP_SITE_OFFSET_M,
        "lift_clearance_m": LIFT_CLEARANCE_M,
        "grip_point_world": grip_point.tolist(),
        "dynamic_replan_after_pickup": True,
        "pickup_measurement": pickup_measurement,
        "pickup_measured_payload": measured_pickup_payload.as_json(),
        "handoff_target_site": HANDOFF_TARGET_SITE,
        "handoff_target_body": HANDOFF_TARGET_BODY,
        "handoff_target_center_world": target_center.tolist(),
        "handoff_target_point_world": handoff_target_point.tolist(),
        "handoff_target_surface_offset_m": HANDOFF_TARGET_SURFACE_OFFSET_M,
        "handoff_target_vertical_offset_m": HANDOFF_TARGET_VERTICAL_OFFSET_M,
        "handoff_top_direction_world": handoff_top_direction.tolist(),
        "handoff_target_axis_world": target_axis.tolist(),
        "handoff_approach_axis_world": handoff_plan.approach_axis.tolist(),
        "handoff_axis_dot": float(np.dot(handoff_plan.approach_axis, target_axis)),
        "handoff_transition_mode": "fixed_post_pickup_tcp",
        "handoff_transition_point_world": measured_pickup_payload.tcp_world.tolist(),
        "handoff_local_y_world_z": float(handoff_plan.handoff_R[2, 1]),
        "handoff_local_y_world_z_tolerance": HANDOFF_LOCAL_Y_WORLD_Z_TOLERANCE,
        "handoff_roll_deg": handoff_plan.roll_deg,
        "handoff_failures": list(handoff_plan.failures),
        "handoff_target_correction_world": target_correction.tolist(),
        "handoff_correction_history": correction_history,
        "pipette_hook_reference_local": PIPETTE_HOOK_REFERENCE_LOCAL.tolist(),
        "hook_offset_tcp_local": hook_offset_tcp_local.tolist(),
        "ideal_hook_offset_tcp_local": ideal_hook_offset_tcp_local.tolist(),
        "payload_offset_tcp_local": payload_offset_tcp_local.tolist(),
        "ideal_payload_offset_tcp_local": ideal_payload_offset_tcp_local.tolist(),
        "payload_R_tcp": payload_R_tcp.tolist(),
        "ideal_payload_R_tcp": ideal_payload_R_tcp.tolist(),
        "payload_collision_check": payload_collision_report.as_json(),
        "handoff_standoff_m": HANDOFF_STANDOFF_M,
        "pre_handoff_hook_point_world": handoff_plan.pre_hook_point.tolist(),
        "final_handoff_tcp_point_world": handoff_plan.final_tcp_point.tolist(),
        "task_success": task_success,
        "dynamics": dynamics_metrics,
        "rrt": {
            "pregrasp": pre_result.__dict__,
        },
        "cartesian": {
            "leveled_pregrasp_waypoints": int(leveled_pregrasp_path.shape[0]),
            "grasp_waypoints": int(grasp_path.shape[0]),
            "lift_waypoints": int(lift_path.shape[0]),
            "pre_handoff_waypoints": int(handoff_plan.pre_path.shape[0]),
            "hook_insert_waypoints": int(handoff_plan.insert_path.shape[0]),
            "retreat_waypoints": int(retreat_path.shape[0]),
        },
    }
    for section in summary["rrt"].values():
        section["path"] = f"{len(section['path'])} waypoints"
    summary_path = output_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    video_path = None
    if args.record_video:
        video_path = output_dir / "piper_gripper_pipette_handoff_expert.mp4"
        render_video(planner.model, qpos_array, video_path, stride=args.video_stride)

    print(f"Wrote trajectory: {npz_path}")
    print(f"Wrote summary: {summary_path}")
    if video_path is not None:
        print(f"Wrote video: {video_path}")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
