"""Generate a 12-block convex ring proxy for pipette-tip mouth collision.

MuJoCo mesh geoms use convex collision behavior, so a single concave/hollow
mesh is not suitable for a real open bore. This generator creates one convex
wedge mesh and instantiates it 12 times around the tip mouth, leaving a real
center opening between independent convex geoms.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_UPPER_MESH_OUT = PROJECT_ROOT / "models/piper_aero_hand/assets/tip_200ul_upper_ring_wedge_12.obj"
DEFAULT_LOWER_MESH_OUT = PROJECT_ROOT / "models/piper_aero_hand/assets/tip_200ul_lower_cone_wedge_12.obj"
DEFAULT_SCENE_OUT = PROJECT_ROOT / "models/piper_aero_hand/scenes/tip_ring_proxy_collision_check.xml"
AUTOBIO_ASSETS = Path("/data/tianang/projects/AutoBio/autobio/assets")
TIP_VISUAL = AUTOBIO_ASSETS / "container/tip_200ul_vis/visual.obj"
TIP_SOLID_COLLISION = AUTOBIO_ASSETS / "container/tip_200ul_col/tip_collision_0.obj"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upper-mesh-out", type=Path, default=DEFAULT_UPPER_MESH_OUT)
    parser.add_argument("--lower-mesh-out", type=Path, default=DEFAULT_LOWER_MESH_OUT)
    parser.add_argument("--scene-out", type=Path, default=DEFAULT_SCENE_OUT)
    parser.add_argument("--blocks", type=int, default=12)
    parser.add_argument("--fill", type=float, default=0.92, help="Angular fill fraction for each block; <1 leaves small gaps.")
    parser.add_argument("--inner-top-mm", type=float, default=2.696914)
    parser.add_argument("--inner-bottom-mm", type=float, default=2.15)
    parser.add_argument("--outer-top-mm", type=float, default=2.9)
    parser.add_argument("--outer-bottom-mm", type=float, default=2.9)
    parser.add_argument("--top-z-mm", type=float, default=0.0)
    parser.add_argument("--bottom-z-mm", type=float, default=-16.0)
    return parser.parse_args()


def vertex(radius_mm: float, angle_rad: float, z_mm: float) -> tuple[float, float, float]:
    return (radius_mm * math.cos(angle_rad), radius_mm * math.sin(angle_rad), z_mm)


def wedge_vertices(
    *,
    blocks: int,
    fill: float,
    inner_top_mm: float,
    inner_bottom_mm: float,
    outer_top_mm: float,
    outer_bottom_mm: float,
    top_z_mm: float,
    bottom_z_mm: float,
) -> list[tuple[float, float, float]]:
    half_angle = math.pi / float(blocks) * float(fill)
    a0 = -half_angle
    a1 = half_angle
    return [
        vertex(inner_top_mm, a0, top_z_mm),
        vertex(outer_top_mm, a0, top_z_mm),
        vertex(outer_top_mm, a1, top_z_mm),
        vertex(inner_top_mm, a1, top_z_mm),
        vertex(inner_bottom_mm, a0, bottom_z_mm),
        vertex(outer_bottom_mm, a0, bottom_z_mm),
        vertex(outer_bottom_mm, a1, bottom_z_mm),
        vertex(inner_bottom_mm, a1, bottom_z_mm),
    ]


def write_wedge_obj(
    path: Path,
    *,
    blocks: int,
    fill: float,
    inner_top_mm: float,
    inner_bottom_mm: float,
    outer_top_mm: float,
    outer_bottom_mm: float,
    top_z_mm: float,
    bottom_z_mm: float,
    object_name: str,
) -> None:
    vertices = wedge_vertices(
        blocks=blocks,
        fill=fill,
        inner_top_mm=inner_top_mm,
        inner_bottom_mm=inner_bottom_mm,
        outer_top_mm=outer_top_mm,
        outer_bottom_mm=outer_bottom_mm,
        top_z_mm=top_z_mm,
        bottom_z_mm=bottom_z_mm,
    )
    faces = [
        (1, 2, 3),
        (1, 3, 4),
        (5, 8, 7),
        (5, 7, 6),
        (1, 5, 6),
        (1, 6, 2),
        (2, 6, 7),
        (2, 7, 3),
        (3, 7, 8),
        (3, 8, 4),
        (4, 8, 5),
        (4, 5, 1),
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/debug/generate_tip_ring_proxy_collision.py\n")
        f.write("# One convex wedge. Instantiate around +Z to form a 12-block tip collision proxy.\n")
        f.write("# Units are millimeters; MJCF should use scale=\"0.001 0.001 0.001\".\n")
        f.write(f"o {object_name}\n")
        for x, y, z in vertices:
            f.write(f"v {x:.8f} {y:.8f} {z:.8f}\n")
        for a, b, c in faces:
            f.write(f"f {a} {b} {c}\n")


def ring_geoms(blocks: int, *, x_offset: float = 0.04) -> str:
    lines = []
    for i in range(blocks):
        angle = 2.0 * math.pi * i / blocks
        lines.append(
            "      "
            f'<geom name="ring_block_{i:02d}" type="mesh" mesh="tip_upper_ring_wedge" '
            f'pos="{x_offset:.6f} 0 0.07" euler="0 0 {angle:.12g}" group="3" material="collision_ring" />'
        )
    return "\n".join(lines)


def cone_geoms(blocks: int, *, x_offset: float = 0.04) -> str:
    lines = []
    for i in range(blocks):
        angle = 2.0 * math.pi * i / blocks
        lines.append(
            "      "
            f'<geom name="cone_block_{i:02d}" type="mesh" mesh="tip_lower_cone_wedge" '
            f'pos="{x_offset:.6f} 0 0.07" euler="0 0 {angle:.12g}" group="3" material="collision_cone" />'
        )
    return "\n".join(lines)


def write_scene(path: Path, args: argparse.Namespace) -> None:
    upper_mesh_rel = Path("../assets") / args.upper_mesh_out.name
    lower_mesh_rel = Path("../assets") / args.lower_mesh_out.name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""<mujoco model="tip_ring_proxy_collision_check">
  <compiler angle="radian" />
  <option timestep="0.002" integrator="implicitfast" cone="elliptic" />

  <visual>
    <headlight diffuse="0.7 0.7 0.7" ambient="0.35 0.35 0.35" specular="0.1 0.1 0.1" />
    <global azimuth="135" elevation="-20" offwidth="1280" offheight="720" />
  </visual>

  <asset>
    <texture name="grid" type="2d" builtin="checker" width="512" height="512" rgb1="0.24 0.24 0.24" rgb2="0.31 0.31 0.31" />
    <material name="floor_grid" texture="grid" texrepeat="4 4" reflectance="0.08" />
    <material name="tip_clear" rgba="1 1 1 0.35" />
    <material name="collision_original" rgba="1 0.45 0.1 0.35" />
    <material name="collision_ring" rgba="0.1 0.65 1 0.45" />
    <material name="collision_cone" rgba="0.75 0.75 0.75 0.45" />
    <material name="connector_ref" rgba="0.95 0.1 0.1 0.75" />

    <mesh name="tip_visual" file="{TIP_VISUAL}" scale="0.001 0.001 0.001" />
    <mesh name="tip_original_collision" file="{TIP_SOLID_COLLISION}" scale="0.001 0.001 0.001" />
    <mesh name="tip_upper_ring_wedge" file="{upper_mesh_rel}" scale="0.001 0.001 0.001" />
    <mesh name="tip_lower_cone_wedge" file="{lower_mesh_rel}" scale="0.001 0.001 0.001" />
  </asset>

  <worldbody>
    <light name="key" pos="0.25 -0.55 0.7" dir="-0.3 0.7 -1" diffuse="0.8 0.8 0.8" />
    <geom name="floor" type="plane" size="0.15 0.12 0.02" material="floor_grid" />

    <body name="original_solid_tip" pos="-0.04 0 0.07">
      <geom name="original_visual" type="mesh" contype="0" conaffinity="0" group="2" mesh="tip_visual" material="tip_clear" />
      <geom name="original_lower_solid_collision" type="mesh" group="3" mesh="tip_original_collision" material="collision_original" />
      <geom name="original_upper_solid_collision" size="0.00287797 0.008" pos="0 0 -0.008" type="cylinder" group="3" material="collision_original" />
      <geom name="original_connector_reference" size="0.00199955 0.012" pos="0 0 0.004" type="cylinder" contype="0" conaffinity="0" group="5" material="connector_ref" />
    </body>

    <body name="ring_proxy_tip">
      <geom name="ring_proxy_visual" type="mesh" contype="0" conaffinity="0" group="2" mesh="tip_visual" pos="0.04 0 0.07" material="tip_clear" />
{ring_geoms(args.blocks)}
{cone_geoms(args.blocks)}
      <geom name="ring_proxy_connector_reference" size="0.00199955 0.012" pos="0.04 0 0.074" type="cylinder" contype="0" conaffinity="0" group="5" material="connector_ref" />
    </body>

    <camera name="check_camera" pos="0 -0.18 0.095" xyaxes="1 0 0 0 0.25 0.97" />
  </worldbody>
</mujoco>
""",
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    if args.blocks < 3:
        raise SystemExit("--blocks must be at least 3")
    if not 0.1 <= args.fill <= 1.0:
        raise SystemExit("--fill must be in [0.1, 1.0]")
    write_wedge_obj(
        args.upper_mesh_out,
        blocks=args.blocks,
        fill=args.fill,
        inner_top_mm=args.inner_top_mm,
        inner_bottom_mm=args.inner_bottom_mm,
        outer_top_mm=args.outer_top_mm,
        outer_bottom_mm=args.outer_bottom_mm,
        top_z_mm=args.top_z_mm,
        bottom_z_mm=args.bottom_z_mm,
        object_name="tip_200ul_upper_ring_wedge_12",
    )
    write_wedge_obj(
        args.lower_mesh_out,
        blocks=args.blocks,
        fill=args.fill,
        inner_top_mm=1.998000,
        inner_bottom_mm=0.196697,
        outer_top_mm=2.900000,
        outer_bottom_mm=0.400000,
        top_z_mm=-16.0,
        bottom_z_mm=-50.0,
        object_name="tip_200ul_lower_cone_wedge_12",
    )
    write_scene(args.scene_out, args)
    print(args.upper_mesh_out)
    print(args.lower_mesh_out)
    print(args.scene_out)
    print(f"blocks={args.blocks} fill={args.fill}")
    print(f"inner_top_diameter_mm={2.0 * args.inner_top_mm:.6f}")
    print(f"inner_bottom_diameter_mm={2.0 * args.inner_bottom_mm:.6f}")
    print("connector_diameter_mm=3.9991")


if __name__ == "__main__":
    main()
