"""Generate a hollow pipette-tip collision mesh for MuJoCo inspection.

This is an experimental asset generator for A2 tip attachment work. It does
not modify AutoBio assets. The generated mesh uses the measured inner/outer
radii from AutoBio's 200 uL tip visual mesh and creates a double-wall tip with
a through bore.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import math


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = PROJECT_ROOT / "models/piper_aero_hand/assets/tip_200ul_hollow_visual_inner_collision.obj"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--segments", type=int, default=64)
    return parser.parse_args()


def ring(radius_mm: float, z_mm: float, segments: int) -> list[tuple[float, float, float]]:
    return [
        (
            radius_mm * math.cos(2.0 * math.pi * i / segments),
            radius_mm * math.sin(2.0 * math.pi * i / segments),
            z_mm,
        )
        for i in range(segments)
    ]


def add_side_faces(faces: list[tuple[int, int, int]], lower_start: int, upper_start: int, segments: int, *, reverse: bool = False) -> None:
    for i in range(segments):
        j = (i + 1) % segments
        a = lower_start + i
        b = lower_start + j
        c = upper_start + j
        d = upper_start + i
        if reverse:
            faces.append((a, c, b))
            faces.append((a, d, c))
        else:
            faces.append((a, b, c))
            faces.append((a, c, d))


def add_annulus_faces(
    faces: list[tuple[int, int, int]],
    outer_start: int,
    inner_start: int,
    segments: int,
    *,
    normal_positive_z: bool,
) -> None:
    for i in range(segments):
        j = (i + 1) % segments
        oi = outer_start + i
        oj = outer_start + j
        ii = inner_start + i
        ij = inner_start + j
        if normal_positive_z:
            faces.append((oi, oj, ij))
            faces.append((oi, ij, ii))
        else:
            faces.append((oi, ij, oj))
            faces.append((oi, ii, ij))


def write_obj(path: Path, vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/debug/generate_hollow_tip_collision_mesh.py\n")
        f.write("# Units are millimeters; MJCF should use scale=\"0.001 0.001 0.001\".\n")
        f.write("o tip_200ul_hollow_visual_inner_collision\n")
        for x, y, z in vertices:
            f.write(f"v {x:.8f} {y:.8f} {z:.8f}\n")
        for a, b, c in faces:
            f.write(f"f {a} {b} {c}\n")


def main() -> None:
    args = parse_args()
    if args.segments < 12:
        raise SystemExit("--segments must be at least 12")

    # Measured from AutoBio assets/container/tip_200ul_vis/visual.obj.
    # Coordinates are in OBJ millimeters before the MJCF 0.001 scale.
    levels = [
        {"z": 0.0, "outer": 2.900000, "inner": 2.696914},
        {"z": -15.8, "outer": 2.696914, "inner": 1.804097},
        {"z": -16.0, "outer": 2.900000, "inner": 1.998000},
        {"z": -50.0, "outer": 0.400000, "inner": 0.196697},
    ]

    vertices: list[tuple[float, float, float]] = []
    outer_starts: list[int] = []
    inner_starts: list[int] = []
    for level in levels:
        outer_starts.append(len(vertices) + 1)
        vertices.extend(ring(level["outer"], level["z"], args.segments))
        inner_starts.append(len(vertices) + 1)
        vertices.extend(ring(level["inner"], level["z"], args.segments))

    faces: list[tuple[int, int, int]] = []
    for k in range(len(levels) - 1):
        add_side_faces(faces, outer_starts[k], outer_starts[k + 1], args.segments)
        add_side_faces(faces, inner_starts[k], inner_starts[k + 1], args.segments, reverse=True)

    add_annulus_faces(faces, outer_starts[0], inner_starts[0], args.segments, normal_positive_z=True)
    add_annulus_faces(faces, outer_starts[-1], inner_starts[-1], args.segments, normal_positive_z=False)

    write_obj(args.out, vertices, faces)
    print(args.out)
    print(f"vertices={len(vertices)} faces={len(faces)} segments={args.segments}")
    print("top_inner_diameter_mm=5.393828")
    print("connector_diameter_mm=3.9991")


if __name__ == "__main__":
    main()
